# Generated by Django 5.0.4 on 2025-02-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_name_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Initials', models.CharField(max_length=50)),
                ('Age', models.CharField(max_length=50)),
                ('Speciality', models.CharField(max_length=50)),
                ('Clas', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
