# Generated by Django 4.2.20 on 2025-03-29 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_student_options_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
